module.exports = {
  'acetaminophen': 'paracetamol',
  'baby carriage': 'pram',
  'band-aid': 'Elastoplast',
  'bangs': 'fringe',
  'cell phone': 'mobile',
  'cellphone': 'mobile',
  'checkers': 'draughts',
  'checking account': 'current account',
  'cilantro': 'coriander',
  'condo': 'flat',
  'cotton candy': 'candy floss',
  'counterclockwise': 'anti-clockwise',
  'diaper': 'nappy',
  'dish towel': 'tea towel',
  'dish soap': 'washing-up liquid',
  'driver\'s license': 'driving licence',
  'drugstore': 'chemist',
  'dumpster': 'skip',
  'eggplant': 'aubergine',
  'eraser': 'rubber',
  'expressway': 'motorway',
  'fanny pack': 'bum bag',
  'faucet': 'tap',
  'flashlight': 'torch',
  'freeway': 'motorway',
  'fries': 'chips',
  'french fries': 'chips',
  'gasoline': 'petrol',
  'garbage can': 'dustbin',
  'ladybug': 'ladybird',
  'license plate': 'number plate',
  'math': 'maths',
  'mom': 'mum',
  'parking garage': 'car park',
  'parking lot': 'car park',
  'play hooky': 'bunk off',
  'popsicle': 'ice lolly',
  'public holiday': 'bank holiday',
  'realtor': 'estate agent',
  'rube goldberg device': 'Heath Robinson device',
  'rube goldberg machine': 'Heath Robinson device',
  'rutabaga': 'swede',
  'sidewalk': 'pavement',
  'sneaker': 'trainer',
  'sneakers': 'trainers',
  'soccer': 'football',
  'station wagon': 'estate car',
  'swap meet': 'car boot sale',
  'takeout': 'takeaway',
  'trash': 'rubbish',
  'trashcan': 'bin',
  'tylenol': 'paracetamol',
  'vacationer': 'holidaymaker',
  'windshield': 'windscreen',
  'zip code': 'postcode',
  'zipper': 'zip',
  'zucchini': 'courgette'
};
