module.exports = {
  'anti-clockwise': 'counterclockwise',
  'aubergine': 'eggplant',
  'bank holiday': 'public holiday',
  'biccie': 'cookie',
  'bicky': 'cookie',
  'bikky': 'cookie',
  'bits and bobs': 'odds and ends',
  'bum bag': 'fanny pack',
  'candy floss': 'cotton candy',
  'car boot sale': 'swap meet',
  'car boot': 'trunk',
  'car park': 'parking lot',
  'cash machine': 'ATM',
  'chippy': 'fish-and-chip shop',
  'chip shop': 'fish-and-chip shop',
  'clingfilm': 'plastic wrap',
  'courgette': 'zucchini',
  'crisps': 'potato chips',
  'current account': 'checking account',
  'draughts': 'checkers',
  'driving licence': 'driver\'s license',
  'dustbin': 'trash can',
  'estate agent': 'real estate agent',
  'estate car': 'station wagon',
  'footie': 'soccer',
  'funfair': 'carnival',
  'heath robinson device': 'rube goldberg device',
  'high street': 'main street',
  'holidaymaker': 'vacationer',
  'ice lolly': 'popsicle',
  'ladybird': 'ladybug',
  'lorry': 'truck',
  'maths': 'math',
  'motorway': 'freeway',
  'nappy': 'diaper',
  'number plate': 'license plate',
  'paracetamol': 'Tylenol',
  'petrol': 'gasoline',
  'pram': 'stroller',
  'self-raising flour': 'self-rising flour',
  'shopping trolley': 'shopping cart',
  'skirting board': 'baseboard',
  'takeaway': 'takeout',
  'trainers': 'sneakers',
  'trousers': 'pants',
  'washing-up liquid': 'dish soap',
  'windscreen': 'windshield',
  'zebra crossing': 'crosswalk'
};
